# Generated by Django 4.1.7 on 2023-03-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0002_alter_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
